### ISSUE TITLE
Use project_dir as a root path to avoid putting the project path in the database

### ISSUE THREAD

**Issue by bvisonl** [ntidev/EmailBundle#3]
Instead of having the full project path (/var/www/html/project/app/spool/default) use the container's parameter `kernel.project_dir` and use that as base for the path. This way you will only have to put /app/spool/default in the database and if the project later lives in another folder it won't affect the database. @ealcantara22

**Comment by ealcantara22** [comment]
we covered this in version v3.0.4.
